/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as NowPlayingRouteImport } from './routes/now-playing'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LabelDashboardRouteImport } from './routes/label-dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollabsRouteImport } from './routes/collabs'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BecomeArtistRouteImport } from './routes/become-artist'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtistStudioRouteImport } from './routes/artist-studio'
import { Route as ArtistProfileEditRouteImport } from './routes/artist-profile-edit'
import { Route as ArtistDashboardRouteImport } from './routes/artist-dashboard'
import { Route as ApplyLabelRouteImport } from './routes/apply-label'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabelsIndexRouteImport } from './routes/labels.index'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as LabelsSlugRouteImport } from './routes/labels.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as ArtistsIdRouteImport } from './routes/artists.$id'
import { Route as ApiPublicLencoWebhookRouteImport } from './routes/api/public/lenco-webhook'
import { Route as ApiPublicDpoWebhookRouteImport } from './routes/api/public/dpo-webhook'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const NowPlayingRoute = NowPlayingRouteImport.update({
  id: '/now-playing',
  path: '/now-playing',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelDashboardRoute = LabelDashboardRouteImport.update({
  id: '/label-dashboard',
  path: '/label-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabsRoute = CollabsRouteImport.update({
  id: '/collabs',
  path: '/collabs',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeArtistRoute = BecomeArtistRouteImport.update({
  id: '/become-artist',
  path: '/become-artist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistStudioRoute = ArtistStudioRouteImport.update({
  id: '/artist-studio',
  path: '/artist-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistProfileEditRoute = ArtistProfileEditRouteImport.update({
  id: '/artist-profile-edit',
  path: '/artist-profile-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistDashboardRoute = ArtistDashboardRouteImport.update({
  id: '/artist-dashboard',
  path: '/artist-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyLabelRoute = ApplyLabelRouteImport.update({
  id: '/apply-label',
  path: '/apply-label',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelsIndexRoute = LabelsIndexRouteImport.update({
  id: '/labels/',
  path: '/labels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelsSlugRoute = LabelsSlugRouteImport.update({
  id: '/labels/$slug',
  path: '/labels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const ArtistsIdRoute = ArtistsIdRouteImport.update({
  id: '/artists/$id',
  path: '/artists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLencoWebhookRoute = ApiPublicLencoWebhookRouteImport.update({
  id: '/api/public/lenco-webhook',
  path: '/api/public/lenco-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDpoWebhookRoute = ApiPublicDpoWebhookRouteImport.update({
  id: '/api/public/dpo-webhook',
  path: '/api/public/dpo-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/albums': typeof AlbumsRoute
  '/apply-label': typeof ApplyLabelRoute
  '/artist-dashboard': typeof ArtistDashboardRoute
  '/artist-profile-edit': typeof ArtistProfileEditRoute
  '/artist-studio': typeof ArtistStudioRoute
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/browse': typeof BrowseRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/collabs': typeof CollabsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/label-dashboard': typeof LabelDashboardRoute
  '/library': typeof LibraryRoute
  '/now-playing': typeof NowPlayingRoute
  '/playlists': typeof PlaylistsRoute
  '/profile': typeof ProfileRoute
  '/radio': typeof RadioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/superadmin': typeof SuperadminRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/labels/$slug': typeof LabelsSlugRoute
  '/artists/': typeof ArtistsIndexRoute
  '/labels/': typeof LabelsIndexRoute
  '/api/public/dpo-webhook': typeof ApiPublicDpoWebhookRoute
  '/api/public/lenco-webhook': typeof ApiPublicLencoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/albums': typeof AlbumsRoute
  '/apply-label': typeof ApplyLabelRoute
  '/artist-dashboard': typeof ArtistDashboardRoute
  '/artist-profile-edit': typeof ArtistProfileEditRoute
  '/artist-studio': typeof ArtistStudioRoute
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/browse': typeof BrowseRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/collabs': typeof CollabsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/label-dashboard': typeof LabelDashboardRoute
  '/library': typeof LibraryRoute
  '/now-playing': typeof NowPlayingRoute
  '/playlists': typeof PlaylistsRoute
  '/profile': typeof ProfileRoute
  '/radio': typeof RadioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/superadmin': typeof SuperadminRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/labels/$slug': typeof LabelsSlugRoute
  '/artists': typeof ArtistsIndexRoute
  '/labels': typeof LabelsIndexRoute
  '/api/public/dpo-webhook': typeof ApiPublicDpoWebhookRoute
  '/api/public/lenco-webhook': typeof ApiPublicLencoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/albums': typeof AlbumsRoute
  '/apply-label': typeof ApplyLabelRoute
  '/artist-dashboard': typeof ArtistDashboardRoute
  '/artist-profile-edit': typeof ArtistProfileEditRoute
  '/artist-studio': typeof ArtistStudioRoute
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/browse': typeof BrowseRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/collabs': typeof CollabsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/label-dashboard': typeof LabelDashboardRoute
  '/library': typeof LibraryRoute
  '/now-playing': typeof NowPlayingRoute
  '/playlists': typeof PlaylistsRoute
  '/profile': typeof ProfileRoute
  '/radio': typeof RadioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/superadmin': typeof SuperadminRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/labels/$slug': typeof LabelsSlugRoute
  '/artists/': typeof ArtistsIndexRoute
  '/labels/': typeof LabelsIndexRoute
  '/api/public/dpo-webhook': typeof ApiPublicDpoWebhookRoute
  '/api/public/lenco-webhook': typeof ApiPublicLencoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/albums'
    | '/apply-label'
    | '/artist-dashboard'
    | '/artist-profile-edit'
    | '/artist-studio'
    | '/auth'
    | '/become-artist'
    | '/browse'
    | '/checkout'
    | '/collabs'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/label-dashboard'
    | '/library'
    | '/now-playing'
    | '/playlists'
    | '/profile'
    | '/radio'
    | '/reset-password'
    | '/search'
    | '/subscriptions'
    | '/superadmin'
    | '/artists/$id'
    | '/checkout/success'
    | '/labels/$slug'
    | '/artists/'
    | '/labels/'
    | '/api/public/dpo-webhook'
    | '/api/public/lenco-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/albums'
    | '/apply-label'
    | '/artist-dashboard'
    | '/artist-profile-edit'
    | '/artist-studio'
    | '/auth'
    | '/become-artist'
    | '/browse'
    | '/checkout'
    | '/collabs'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/label-dashboard'
    | '/library'
    | '/now-playing'
    | '/playlists'
    | '/profile'
    | '/radio'
    | '/reset-password'
    | '/search'
    | '/subscriptions'
    | '/superadmin'
    | '/artists/$id'
    | '/checkout/success'
    | '/labels/$slug'
    | '/artists'
    | '/labels'
    | '/api/public/dpo-webhook'
    | '/api/public/lenco-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/albums'
    | '/apply-label'
    | '/artist-dashboard'
    | '/artist-profile-edit'
    | '/artist-studio'
    | '/auth'
    | '/become-artist'
    | '/browse'
    | '/checkout'
    | '/collabs'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/label-dashboard'
    | '/library'
    | '/now-playing'
    | '/playlists'
    | '/profile'
    | '/radio'
    | '/reset-password'
    | '/search'
    | '/subscriptions'
    | '/superadmin'
    | '/artists/$id'
    | '/checkout/success'
    | '/labels/$slug'
    | '/artists/'
    | '/labels/'
    | '/api/public/dpo-webhook'
    | '/api/public/lenco-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlbumsRoute: typeof AlbumsRoute
  ApplyLabelRoute: typeof ApplyLabelRoute
  ArtistDashboardRoute: typeof ArtistDashboardRoute
  ArtistProfileEditRoute: typeof ArtistProfileEditRoute
  ArtistStudioRoute: typeof ArtistStudioRoute
  AuthRoute: typeof AuthRoute
  BecomeArtistRoute: typeof BecomeArtistRoute
  BrowseRoute: typeof BrowseRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CollabsRoute: typeof CollabsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LabelDashboardRoute: typeof LabelDashboardRoute
  LibraryRoute: typeof LibraryRoute
  NowPlayingRoute: typeof NowPlayingRoute
  PlaylistsRoute: typeof PlaylistsRoute
  ProfileRoute: typeof ProfileRoute
  RadioRoute: typeof RadioRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SuperadminRoute: typeof SuperadminRoute
  ArtistsIdRoute: typeof ArtistsIdRoute
  LabelsSlugRoute: typeof LabelsSlugRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  LabelsIndexRoute: typeof LabelsIndexRoute
  ApiPublicDpoWebhookRoute: typeof ApiPublicDpoWebhookRoute
  ApiPublicLencoWebhookRoute: typeof ApiPublicLencoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now-playing': {
      id: '/now-playing'
      path: '/now-playing'
      fullPath: '/now-playing'
      preLoaderRoute: typeof NowPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/label-dashboard': {
      id: '/label-dashboard'
      path: '/label-dashboard'
      fullPath: '/label-dashboard'
      preLoaderRoute: typeof LabelDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collabs': {
      id: '/collabs'
      path: '/collabs'
      fullPath: '/collabs'
      preLoaderRoute: typeof CollabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-artist': {
      id: '/become-artist'
      path: '/become-artist'
      fullPath: '/become-artist'
      preLoaderRoute: typeof BecomeArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist-studio': {
      id: '/artist-studio'
      path: '/artist-studio'
      fullPath: '/artist-studio'
      preLoaderRoute: typeof ArtistStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist-profile-edit': {
      id: '/artist-profile-edit'
      path: '/artist-profile-edit'
      fullPath: '/artist-profile-edit'
      preLoaderRoute: typeof ArtistProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist-dashboard': {
      id: '/artist-dashboard'
      path: '/artist-dashboard'
      fullPath: '/artist-dashboard'
      preLoaderRoute: typeof ArtistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-label': {
      id: '/apply-label'
      path: '/apply-label'
      fullPath: '/apply-label'
      preLoaderRoute: typeof ApplyLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labels/': {
      id: '/labels/'
      path: '/labels'
      fullPath: '/labels/'
      preLoaderRoute: typeof LabelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labels/$slug': {
      id: '/labels/$slug'
      path: '/labels/$slug'
      fullPath: '/labels/$slug'
      preLoaderRoute: typeof LabelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/artists/$id': {
      id: '/artists/$id'
      path: '/artists/$id'
      fullPath: '/artists/$id'
      preLoaderRoute: typeof ArtistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lenco-webhook': {
      id: '/api/public/lenco-webhook'
      path: '/api/public/lenco-webhook'
      fullPath: '/api/public/lenco-webhook'
      preLoaderRoute: typeof ApiPublicLencoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dpo-webhook': {
      id: '/api/public/dpo-webhook'
      path: '/api/public/dpo-webhook'
      fullPath: '/api/public/dpo-webhook'
      preLoaderRoute: typeof ApiPublicDpoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlbumsRoute: AlbumsRoute,
  ApplyLabelRoute: ApplyLabelRoute,
  ArtistDashboardRoute: ArtistDashboardRoute,
  ArtistProfileEditRoute: ArtistProfileEditRoute,
  ArtistStudioRoute: ArtistStudioRoute,
  AuthRoute: AuthRoute,
  BecomeArtistRoute: BecomeArtistRoute,
  BrowseRoute: BrowseRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CollabsRoute: CollabsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LabelDashboardRoute: LabelDashboardRoute,
  LibraryRoute: LibraryRoute,
  NowPlayingRoute: NowPlayingRoute,
  PlaylistsRoute: PlaylistsRoute,
  ProfileRoute: ProfileRoute,
  RadioRoute: RadioRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SuperadminRoute: SuperadminRoute,
  ArtistsIdRoute: ArtistsIdRoute,
  LabelsSlugRoute: LabelsSlugRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  LabelsIndexRoute: LabelsIndexRoute,
  ApiPublicDpoWebhookRoute: ApiPublicDpoWebhookRoute,
  ApiPublicLencoWebhookRoute: ApiPublicLencoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
