/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BecomeArtistRouteImport } from './routes/become-artist'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtistStudioRouteImport } from './routes/artist-studio'
import { Route as ArtistDashboardRouteImport } from './routes/artist-dashboard'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as ArtistsIdRouteImport } from './routes/artists.$id'
import { Route as ApiPublicDpoWebhookRouteImport } from './routes/api/public/dpo-webhook'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeArtistRoute = BecomeArtistRouteImport.update({
  id: '/become-artist',
  path: '/become-artist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistStudioRoute = ArtistStudioRouteImport.update({
  id: '/artist-studio',
  path: '/artist-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistDashboardRoute = ArtistDashboardRouteImport.update({
  id: '/artist-dashboard',
  path: '/artist-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIdRoute = ArtistsIdRouteImport.update({
  id: '/artists/$id',
  path: '/artists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDpoWebhookRoute = ApiPublicDpoWebhookRouteImport.update({
  id: '/api/public/dpo-webhook',
  path: '/api/public/dpo-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/albums': typeof AlbumsRoute
  '/artist-dashboard': typeof ArtistDashboardRoute
  '/artist-studio': typeof ArtistStudioRoute
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/browse': typeof BrowseRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/superadmin': typeof SuperadminRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/artists/': typeof ArtistsIndexRoute
  '/api/public/dpo-webhook': typeof ApiPublicDpoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/albums': typeof AlbumsRoute
  '/artist-dashboard': typeof ArtistDashboardRoute
  '/artist-studio': typeof ArtistStudioRoute
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/browse': typeof BrowseRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/superadmin': typeof SuperadminRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/artists': typeof ArtistsIndexRoute
  '/api/public/dpo-webhook': typeof ApiPublicDpoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/albums': typeof AlbumsRoute
  '/artist-dashboard': typeof ArtistDashboardRoute
  '/artist-studio': typeof ArtistStudioRoute
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/browse': typeof BrowseRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/superadmin': typeof SuperadminRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/artists/': typeof ArtistsIndexRoute
  '/api/public/dpo-webhook': typeof ApiPublicDpoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/albums'
    | '/artist-dashboard'
    | '/artist-studio'
    | '/auth'
    | '/become-artist'
    | '/browse'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/profile'
    | '/subscriptions'
    | '/superadmin'
    | '/artists/$id'
    | '/artists/'
    | '/api/public/dpo-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/albums'
    | '/artist-dashboard'
    | '/artist-studio'
    | '/auth'
    | '/become-artist'
    | '/browse'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/profile'
    | '/subscriptions'
    | '/superadmin'
    | '/artists/$id'
    | '/artists'
    | '/api/public/dpo-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/albums'
    | '/artist-dashboard'
    | '/artist-studio'
    | '/auth'
    | '/become-artist'
    | '/browse'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/profile'
    | '/subscriptions'
    | '/superadmin'
    | '/artists/$id'
    | '/artists/'
    | '/api/public/dpo-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlbumsRoute: typeof AlbumsRoute
  ArtistDashboardRoute: typeof ArtistDashboardRoute
  ArtistStudioRoute: typeof ArtistStudioRoute
  AuthRoute: typeof AuthRoute
  BecomeArtistRoute: typeof BecomeArtistRoute
  BrowseRoute: typeof BrowseRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SuperadminRoute: typeof SuperadminRoute
  ArtistsIdRoute: typeof ArtistsIdRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  ApiPublicDpoWebhookRoute: typeof ApiPublicDpoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-artist': {
      id: '/become-artist'
      path: '/become-artist'
      fullPath: '/become-artist'
      preLoaderRoute: typeof BecomeArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist-studio': {
      id: '/artist-studio'
      path: '/artist-studio'
      fullPath: '/artist-studio'
      preLoaderRoute: typeof ArtistStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist-dashboard': {
      id: '/artist-dashboard'
      path: '/artist-dashboard'
      fullPath: '/artist-dashboard'
      preLoaderRoute: typeof ArtistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$id': {
      id: '/artists/$id'
      path: '/artists/$id'
      fullPath: '/artists/$id'
      preLoaderRoute: typeof ArtistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dpo-webhook': {
      id: '/api/public/dpo-webhook'
      path: '/api/public/dpo-webhook'
      fullPath: '/api/public/dpo-webhook'
      preLoaderRoute: typeof ApiPublicDpoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlbumsRoute: AlbumsRoute,
  ArtistDashboardRoute: ArtistDashboardRoute,
  ArtistStudioRoute: ArtistStudioRoute,
  AuthRoute: AuthRoute,
  BecomeArtistRoute: BecomeArtistRoute,
  BrowseRoute: BrowseRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SuperadminRoute: SuperadminRoute,
  ArtistsIdRoute: ArtistsIdRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  ApiPublicDpoWebhookRoute: ApiPublicDpoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
